name: "Dependabot Automerge - Action"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review   

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: automerge
        uses:
 actions/github-script@v7.0.1
        with:
          script: |
            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');

            try {
              octokit.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE'
              });

              console.log("Pull Request approved by Dependabot");

              await octokit.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });

              console.log("Pull Request merged successfully");
            } catch (error) {
              console.error("Error merging pull request:", error);
              // You can optionally fail the workflow here for further investigation
            }
