name: "Dependabot Automerge - Action"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        uses: actions/github-script@v7.0.1
        with:
          script: |
            console.log(JSON.stringify(context.payload, null, 2)); // Debugging
            const github = require('@actions/github');
            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');
            
            octokit.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
            octokit.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            });
